### ISSUE TITLE
yoga 730 not work.

### ISSUE THREAD

**Issue by ericma15** [lukas-w/yoga-usage-mode#1]
Hi, my laptop is yoga 730.It seems not work. Can you tell me how to find the guid 
of each event?
Thx.

**Comment by lukas-w** [comment]
This module is only intended for the Yoga C940. It looks like your laptop already has support in the Linux kernel, at least https://wiki.archlinux.org/index.php/Lenovo_yoga_730#Tablet_mode claims that the `keyboard automatically disables`.

If it's of interest anyway, IIRC I "reverse engineered" the C940's WMI interface by decoding its BMF at `/sys/bus/wmi/drivers/wmi-bmof/*/bmof` using the `bmf2mof` utility from https://github.com/pali/bmfdec. This yields what you can find in [`c940.mof`](https://github.com/lukas-w/yoga-usage-mode/blob/master/c940.mof) including the relevant GUIDs with human readable descriptions.

**Comment by ericma15** [comment]
Hey, thanks for your replying. In fact, now I find the driver is work on yoga 730. The previous my kernel build may exist some problem. The wmi driver doesn't work well, I recompile it. 
Also the bmof file on my computer can't be decode by bmf2mof. Maybe this lib is not compatice.I will learn bmf by mydelf.
In a word, Thank you.
