### ISSUE TITLE
Works on Lenovo Yoga 13ALC7 (The AMD model of 13ALC6)

### ISSUE THREAD

**Issue by varappdev** [lukas-w/yoga-usage-mode#4]
Just wanted to inform that it works on the laptop mentioned above. A true lifesaver after 4 hours of googling, and made KDE work out of the box with screen rotation as well, so that is a huge plus.

**Comment by aedalzotto** [comment]
Works with 13ALC6 too (also AMD model).
Thanks for this amazing work.

I suggest to add a section in README.md with a list of models that reportedly work.

**Comment by lukas-w** [comment]
Amazing, thanks for letting me know! Added to readme via 3d15f9376f596f64b5ce7c4a68dfb15cc93c77cb.
