### ISSUE TITLE
Does not work on Lenovo Yoga 7 14ACN6

### ISSUE THREAD

**Issue by sidevesh** [lukas-w/yoga-usage-mode#7]
I was waiting for this to land on linux 6.4 so that I can stop using the mutter-auto-rotation arch aur package and get proper tablet mode support,
but looks like this ended up breaking things completely for me and now even with mutter-auto-rotation, I can't get auto-rotation toggle or the on screen keyboard to show up in any mode, my guess is because now system gets SW_TABLET_MODE 0 reported by this module,
I can see it in `evtest`: `/dev/input/event13:	Lenovo Yoga Tablet Mode Control switch`
but on flipping the tablet between modes, it triggers no events and laptop remains stuck on laptop mode.

**Comment by sidevesh** [comment]
Any way I can help debug things to maybe get this to work on my laptop model too ?

**Comment by sidevesh** [comment]
@lukas-w Any way I can help debug this ? This has broken tablet mode, auto rotation and soft keyboard for my laptop.

**Comment by lukas-w** [comment]
I'm not sure what you're asking. If installing this module has broken previously working features for you, I suggest removing it again.

**Comment by sidevesh** [comment]
I hadnt installed this module, I thought this was merged into linux kernel but I think I was wrong, sorry for the confusion.

**Comment by lukas-w** [comment]
No worries, sorry for taking so long to reply!
